Document: mangler
Title: Debian mangler Manual
Author: <insert document author here>
Abstract: This manual describes what mangler is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mangler/mangler.sgml.gz

Format: postscript
Files: /usr/share/doc/mangler/mangler.ps.gz

Format: text
Files: /usr/share/doc/mangler/mangler.text.gz

Format: HTML
Index: /usr/share/doc/mangler/html/index.html
Files: /usr/share/doc/mangler/html/*.html
