.TH MANGLER 1
.SH NAME
mangler \- A VOIP client for connecting to Ventrilo 3.x servers
.SH SYNOPSIS
.B mangler
.PP
.SH DESCRIPTION
Mangler is an open source implementation of a client for connecting to Ventrilo 3.x servers.  It supports keyboard and mouse button push to talk, GSM and Speex codecs, per-user volume control, a full featured server phonebook, the ability to connect to server without adding it to your phonebook, and native PulseAudio support.
.PP
.SH "OTHER INFO"
The website for mangler can be found at http://www.mangler.org/
.PP
.SH AUTHORS
.TP
Eric Kilfoil <ekilfoil@gmail.com>, Daniel Sloof <daniel@mangler.org>

